services:
    notes-app:
        image: notes:latest
        networks:
            - database_mysql
        restart: always
        user: "www-data:www-data"
        ports:
          - '8000:80'
        volumes:
            - ./storage:/var/www/html/storage
            - ./.env.prod:/var/www/html/.env
networks:
    database_mysql:
      external: true
