services:
    # notes-traefik:
    #     command:
    #         - --providers.docker=true
    #         - --providers.docker.exposedbydefault=false
    #         - --providers.docker.network=network
    #         - --entrypoints.notes.address=:80
    #         - --accesslog.filepath=/logs/access.log
    #         - --accesslog.bufferingsize=100
    #         - --log.level=INFO
    #     image: traefik:2.10.5
    #     labels:
    #         - "traefik.enable=true"
    #     networks:
    #         - network
    #     ports:
    #         - "${TRAEFIK_APP_PORT:-80}:80"
    #     restart: always
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock:ro
    #         - ~/traefik/logs:/logs:rw
    notes-app:
        # build:
        #     context: ./
        #     dockerfile: Dockerfile
        image: notes:latest
        # labels:
        #     - "traefik.enable=true"
        #     - "traefik.http.routers.notes.rule=${TRAEFIK_HTTP_ROUTERS:-Host(`localhost`)}"
        #     - "traefik.http.routers.notes.entrypoints=notes"
        #     - "traefik.http.services.notes.loadbalancer.server.port=80"
        networks:
            # - network
            - database_mysql
        restart: always
        user: "www-data:www-data"
        ports:
          - '8000:80'
        volumes:
            - ./storage:/var/www/html/storage
            - ./.env:/var/www/html/.env
networks:
    database_mysql:
      external: true
    network:
        driver: bridge
